version: "3.8"
services:
  roach1:
    container_name: roach1
    image: cockroachdb/cockroach:v20.1.15
    command: start --insecure --join=roach1,roach2,roach3
    ports:
      - "26257:26257"
      - "8111:8080"
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data
    networks:
      - roachnet

  roach2:
    container_name: roach2
    image: cockroachdb/cockroach:v20.1.15
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - ./cockroach-data/roach2:/cockroach/cockroach-data
    depends_on:
      - roach1
    networks:
      - roachnet

  roach3:
    container_name: roach3
    image: cockroachdb/cockroach:v20.1.15
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - ./cockroach-data/roach3:/cockroach/cockroach-data
    depends_on:
      - roach1
    networks:
      - roachnet

networks:
  roachnet:
    driver: bridge
