version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:9.6.24-stretch
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5444:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
        
  redis:
      ports:
        - "6379:6379"
      image: "redis:alpine"
